//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVLC_LIVE_Entities : DbContext
    {
        public MVLC_LIVE_Entities()
            : base("name=MVLC_LIVE_Entities")
        {
        }
        public MVLC_LIVE_Entities(string EnvName)
            : base("name=" + EnvName)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BulkClassHour> BulkClassHours { get; set; }
        public virtual DbSet<ClassDate> ClassDates { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<HoursEntryIssue> HoursEntryIssues { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonClass> PersonClasses { get; set; }
        public virtual DbSet<PersonClassHour> PersonClassHours { get; set; }
        public virtual DbSet<PersonClassHoursHistory> PersonClassHoursHistories { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<SectionContent> SectionContents { get; set; }
        public virtual DbSet<SectionLayout> SectionLayouts { get; set; }
    }
}
