//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonClass
    {
        public int PersonID { get; set; }
        public int ClassID { get; set; }
        public string PersonRole { get; set; }
        public Nullable<System.DateTime> WithdrawDate { get; set; }
        public Nullable<double> RecentHours { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Person Person { get; set; }
    }
}
