//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectionLayout()
        {
            this.SectionContents = new HashSet<SectionContent>();
        }
    
        public int SectionLayoutID { get; set; }
        public string LayoutName { get; set; }
        public string HeaderLink { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string CssClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionContent> SectionContents { get; set; }
    }
}
