//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkClassHour
    {
        public int ClassID { get; set; }
        public Nullable<int> NumberOfStudents { get; set; }
        public Nullable<double> TotalStudentHours { get; set; }
        public Nullable<int> NumberofTutors { get; set; }
        public Nullable<double> TotalTutorHours { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
