//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ClassID { get; set; }
        public Nullable<int> CourseNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Term { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public Nullable<int> TutorID { get; set; }
        public Nullable<double> TotalTutorHours { get; set; }
        public Nullable<double> TotalStudentHours { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public int CourseCourseNumber { get; set; }
        public bool CourseInUse { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
