//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonNote
    {
        public int NoteID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Note { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public string ClosedBy { get; set; }
    }
}
