//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentClasses = new HashSet<StudentClass>();
        }
    
        public int StudentID { get; set; }
        public bool Delete { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int EthnicityID { get; set; }
        public bool Below_Poverty_level { get; set; }
        public bool Is_Homeless { get; set; }
        public bool IsRefugee { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Education { get; set; }
        public string Employed { get; set; }
        public string Years_Complete { get; set; }
        public string Time_Here { get; set; }
        public string Other_Degree_or_Diploma { get; set; }
        public string Country_Earned_ { get; set; }
        public string AgeRange { get; set; }
        public Nullable<int> Where_Earned { get; set; }
        public Nullable<int> FirstLanguage { get; set; }
        public string Country_of_Origin1 { get; set; }
        public bool SpecialNeeds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}
