//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public int TutorID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public bool IsEmployed { get; set; }
        public string Employer { get; set; }
        public bool Has_Diploma_or_GED { get; set; }
        public bool IsExperienced { get; set; }
        public string ExperienceLocation { get; set; }
    }
}
