//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorClass
    {
        public int TutorID { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> NumberStudents { get; set; }
        public Nullable<int> TotalStudentHours { get; set; }
        public Nullable<int> MaxStudentHours { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public string RemovedBy { get; set; }
        public Nullable<System.DateTime> WithdrawDate { get; set; }
        public string WithDrawBy { get; set; }
    }
}
