//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVLC.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonClassHoursHistory
    {
        public int PersonID { get; set; }
        public int ClassID { get; set; }
        public System.DateTime ClassDate { get; set; }
        public Nullable<double> ClassHours { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Person Person { get; set; }
    }
}
